name: Doc

on:
  schedule:
    - cron: '*/9 * * * *'

jobs:
  BlockCypher_CSV_Overwrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make doc
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: make unconf && make doc

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Overwritten by Github Actions - $(date)"
          git push origin main

