name: Write Waiting Time Txs

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  BlockCypher_CSV_Overwrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get blockcypher data 
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: make waitingTxs

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Overwritten by Github Actions - $(date)"
          git push origin main

